# Generated by Django 3.1.2 on 2020-10-24 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beatmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(max_length=25, unique=True)),
                ('beatmapset_id', models.CharField(max_length=25)),
                ('title', models.TextField()),
                ('version', models.TextField()),
                ('artist', models.TextField()),
                ('bpm', models.FloatField()),
                ('creator', models.TextField()),
                ('difficultyrating', models.FloatField()),
                ('diff_aim', models.FloatField()),
                ('diff_speed', models.FloatField()),
                ('diff_size', models.FloatField()),
                ('diff_overall', models.FloatField()),
                ('diff_drain', models.FloatField()),
                ('diff_approach', models.FloatField()),
                ('hit_length', models.IntegerField()),
                ('total_length', models.IntegerField()),
                ('max_combo', models.IntegerField()),
                ('file_md5', models.TextField()),
                ('tags', models.TextField()),
                ('official', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(max_length=25, unique=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('mods', models.IntegerField()),
                ('play_mode', models.IntegerField()),
                ('scoring_type', models.IntegerField()),
                ('team_type', models.IntegerField()),
                ('beatmap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stats.beatmap')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(max_length=25, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('qualifier', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(max_length=25, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stats.division')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField()),
                ('team', models.IntegerField()),
                ('score', models.IntegerField()),
                ('max_combo', models.IntegerField()),
                ('count_50', models.IntegerField()),
                ('count_100', models.IntegerField()),
                ('count_300', models.IntegerField()),
                ('count_miss', models.IntegerField()),
                ('perfect', models.BooleanField()),
                ('passed', models.BooleanField()),
                ('enabled_mods', models.IntegerField(null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stats.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stats.user')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stats.match'),
        ),
    ]
