# Generated by Django 3.1.2 on 2020-10-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default="ZA", max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='country_rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='global_rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
