# Generated by Django 3.1.2 on 2020-10-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20201026_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
