# Generated by Django 3.1.2 on 2020-10-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_mappool_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='beatmap',
            name='identifier',
            field=models.TextField(blank=True, null=True),
        ),
    ]
