# Generated by Django 3.1.2 on 2020-11-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_mappool_download_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chosen_class',
            field=models.TextField(blank=True, null=True),
        ),
    ]
