# Generated by Django 3.1.2 on 2020-11-25 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_beatmap_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beatmap',
            name='division',
        ),
        migrations.AddField(
            model_name='mappool',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stats.division'),
        ),
    ]
