# Generated by Django 3.1.2 on 2020-11-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_auto_20201125_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappool',
            name='division',
        ),
        migrations.AddField(
            model_name='division',
            name='mappools',
            field=models.ManyToManyField(to='stats.MapPool'),
        ),
    ]
