# Generated by Django 3.1.2 on 2020-11-25 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_auto_20201125_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='beatmap',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stats.division'),
        ),
    ]
